export default {
    id: 38962433,
    login: "marcionavarro",
    node_id: "MDQ6VXNlcjM4OTYyNDMz",
    avatar_url: "https://avatars.githubusercontent.com/u/38962433?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/marcionavarro",
    html_url: "https://github.com/marcionavarro",
    followers_url: "https://api.github.com/users/marcionavarro/followers",
    following_url: "https://api.github.com/users/marcionavarro/following{/other_user}",
    gists_url: "https://api.github.com/users/marcionavarro/gists{/gist_id}",
    starred_url: "https://api.github.com/users/marcionavarro/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/marcionavarro/subscriptions",
    organizations_url: "https://api.github.com/users/marcionavarro/orgs",
    repos_url: "https://api.github.com/users/marcionavarro/repos",
    events_url: "https://api.github.com/users/marcionavarro/events{/privacy}",
    received_events_url: "https://api.github.com/users/marcionavarro/received_events",
    type: "User",
    site_admin: false,
    name: "Marcio Navarro",
    company: "Desenvolvedor FullStack",
    blog: "https://www.marcionavarro.com.br",
    location: "Uberlâdia MG",
    email: null,
    hireable: true,
    bio: "Apaixonado por programação, estou sempre a procura de desafios. autodidata sempre me atualizando com o que há de novo em ... CSS, HTML, JS, PHP, WORDPRESS, POO",
    twitter_username: "mnsaipers",
    public_repos: 40,
    public_gists: 0,
    followers: 4,
    following: 6,
    created_at: "2018-05-03T20:50:09Z",
    updated_at: "2024-01-02T02:24:49Z"
};
