export default [
  {
    login: "esin",
    id: 69767,
    node_id: "MDQ6VXNlcjY5NzY3",
    avatar_url: "https://avatars.githubusercontent.com/u/69767?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/esin",
    html_url: "https://github.com/esin",
    followers_url: "https://api.github.com/users/esin/followers",
    following_url: "https://api.github.com/users/esin/following{/other_user}",
    gists_url: "https://api.github.com/users/esin/gists{/gist_id}",
    starred_url: "https://api.github.com/users/esin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/esin/subscriptions",
    organizations_url: "https://api.github.com/users/esin/orgs",
    repos_url: "https://api.github.com/users/esin/repos",
    events_url: "https://api.github.com/users/esin/events{/privacy}",
    received_events_url: "https://api.github.com/users/esin/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "xchanmolx",
    id: 16154263,
    node_id: "MDQ6VXNlcjE2MTU0MjYz",
    avatar_url: "https://avatars.githubusercontent.com/u/16154263?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xchanmolx",
    html_url: "https://github.com/xchanmolx",
    followers_url: "https://api.github.com/users/xchanmolx/followers",
    following_url: "https://api.github.com/users/xchanmolx/following{/other_user}",
    gists_url: "https://api.github.com/users/xchanmolx/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xchanmolx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xchanmolx/subscriptions",
    organizations_url: "https://api.github.com/users/xchanmolx/orgs",
    repos_url: "https://api.github.com/users/xchanmolx/repos",
    events_url: "https://api.github.com/users/xchanmolx/events{/privacy}",
    received_events_url: "https://api.github.com/users/xchanmolx/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "jgcarlosfranca",
    id: 53311165,
    node_id: "MDQ6VXNlcjUzMzExMTY1",
    avatar_url: "https://avatars.githubusercontent.com/u/53311165?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jgcarlosfranca",
    html_url: "https://github.com/jgcarlosfranca",
    followers_url: "https://api.github.com/users/jgcarlosfranca/followers",
    following_url: "https://api.github.com/users/jgcarlosfranca/following{/other_user}",
    gists_url: "https://api.github.com/users/jgcarlosfranca/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jgcarlosfranca/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jgcarlosfranca/subscriptions",
    organizations_url: "https://api.github.com/users/jgcarlosfranca/orgs",
    repos_url: "https://api.github.com/users/jgcarlosfranca/repos",
    events_url: "https://api.github.com/users/jgcarlosfranca/events{/privacy}",
    received_events_url: "https://api.github.com/users/jgcarlosfranca/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "coder-samuel",
    id: 80654468,
    node_id: "MDQ6VXNlcjgwNjU0NDY4",
    avatar_url: "https://avatars.githubusercontent.com/u/80654468?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/coder-samuel",
    html_url: "https://github.com/coder-samuel",
    followers_url: "https://api.github.com/users/coder-samuel/followers",
    following_url: "https://api.github.com/users/coder-samuel/following{/other_user}",
    gists_url: "https://api.github.com/users/coder-samuel/gists{/gist_id}",
    starred_url: "https://api.github.com/users/coder-samuel/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/coder-samuel/subscriptions",
    organizations_url: "https://api.github.com/users/coder-samuel/orgs",
    repos_url: "https://api.github.com/users/coder-samuel/repos",
    events_url: "https://api.github.com/users/coder-samuel/events{/privacy}",
    received_events_url: "https://api.github.com/users/coder-samuel/received_events",
    type: "User",
    site_admin: false
    }
];
